### PR TITLE
[WIP] Rebrand to syndesis.

### PR DESCRIPTION
**Pull request by iocanel**
Test will fail untill we get a release of a rebranded connectors

### CODE REVIEW

**Comment by jimmidyson** [comment]
retest this please

**Comment by jimmidyson** [comment]
@iocanel Can you rebase please?

**Comment by iocanel** [comment]
@jimmidyson: done

**Comment by jimmidyson** [comment]
Build failures caused by a dodgy connectors release that didn't include package names in component metadata due to https://github.com/syndesisio/connectors/pull/45/files#diff-fcc96eefa113bb6a55a2de4a7b729dd8. Fixing up and releasing new version of connectors then will update this PR.

**Comment by jimmidyson** [comment]
This is ready for merge I think, with the one problem that it's not passing on our integration test environment... but that looks like a dodgy issue connecting to jcenter to download a dep. @iocanel WDYT?

**Pull request merged**
