### PR TITLE
[#576] Update filter API to accept just an output data shape instead …

### PR DESCRIPTION
**Pull request by igarashitm**
…of the whole integration

### CODE REVIEW

**Comment by zregvart** [comment]
nit: @igarashitm we use [conventional commits](https://syndesis.io/community/engineering_guidelines/#commit-messages-should-follow-the-conventional-commits-standardized-commit-message-format), so a commit title would look like `chore(filters): Update filter API to accept just an output data shape...` and in the commit message body you would end with `Fixes #576`

**Comment by zregvart** [comment]
@gashcrumb this is what we want for #576, an API change? Or would you prefer to have both options available?

**Comment by igarashitm** [comment]
OK fixed PMD errors and commit message

**Comment by gashcrumb** [comment]
@zregvart yep, the current basic filter UI already passes only the data shape object when calling this API, so this should get that typeahead working again when there's a data shape available.

**Pull request merged**
