### PR TITLE
chore: move sql stored procedure connector to `demo-data.json`

### PR DESCRIPTION
**Pull request by zregvart**
Moves SQL stored procedure connector from `deployment.json` to `demo-data.json` to prevent it from showing up in production.

### CODE REVIEW

**Comment by KurtStam** [comment]
@zregvart I think it makes sense to first commit https://github.com/syndesisio/syndesis-rest/pull/644

**Comment by KurtStam** [comment]
@zregvart  you will need to move both connector and connection now.

**Comment by rhuss** [comment]
retest this please

**Comment by rhuss** [comment]
retest this please

**Comment by rhuss** [comment]
retest this please

**Pull request merged**
