### PR TITLE
fix: #619 Set 25 second keep alive timers on both SSE and WebSocket c…

### PR DESCRIPTION
**Pull request by chirino**
…onnections since open shift likes to close out idle backend server connection.

### CODE REVIEW

**Comment by chirino** [comment]
if someone comes back requesting a different value, lets re-evaluate if we want to make it configurable.

**Comment by chirino** [comment]
retest this please

**Comment by chirino** [comment]
Jenkins seems busted still.

**Comment by rhuss** [comment]
Come on, this can't be our default working mode. There is a reason for testing. I agree that Jenkins is a big PITA with our setup, but we need another solution urgently. Manual merging can't be the new standard // @iocanel let's bring it on are revive our CI discussion in hindsight of the latest troubles. Going to continue on tomorrow ....

**Comment by iocanel** [comment]
@rhuss: Agree. We need a solution ASAP. I am not sure if the particular issues (that we have the last couple of weeks) has anything to do with our setup. It's a regression in one of (kubernetes-plugin, durable-task-plugin) and I am working on it.

**Pull request merged**
