### PR TITLE
[TestSupport] Enable to delete deployments

### PR DESCRIPTION
**Pull request by jknetl**
Enables TestSupport to delete OpenShift deployments.

### CODE REVIEW

**Comment by dsimansk** [comment]
@jimmidyson any hints how to make dependency-ci happy?

**Comment by jimmidyson** [comment]
@dsimansk Looks like dependency-ci has some issues atm - please ignore.

@jknetl Please can you push your branch to your own fork rather than to the origin repo? I'm going to close this PR if you don't mind so you can do that and submit a new PR? Just want to make sure we don't have lots of branches in the origin repo.

**Comment by jknetl** [comment]
@jimmidyson Sure thing. I created new PR #491 and deleted the branch from origin.

**Comment by jimmidyson** [comment]
Thank you!

**Pull request closed without merging**
