### PR TITLE
Tech extension : maven archetype #776

### PR DESCRIPTION
**Pull request by lburgazzoli**

### CODE REVIEW

**Comment by lburgazzoli** [comment]
retest this please

**Comment by KurtStam** [comment]
@lburgazzoli, am I right to assume that we want to maintain this here as we think this project will be the only consumer? If so where are we going to publish the documentation for it?

**Comment by lburgazzoli** [comment]
Mh not sure, what would be the best location for archetypes ?

**Comment by lburgazzoli** [comment]
retest this please

**Comment by lburgazzoli** [comment]
@KurtStam @rhuss would it be ok to keep this in syndesis-rest till we move to monorepo ? then we can make archetype a standalone module

**Comment by rhuss** [comment]
@lburgazzoli looks. Get ready for the move, fasten seatbelts and then when can move when we are over the bridge.

**Pull request merged**
