### PR TITLE
refactor(connectors): Bring back SQL stored connector

### PR DESCRIPTION
**Pull request by zregvart**
This re-enables the SQL stored procedure connector and the accompanying
connection by moving it from `demo-data.json` to `deployment.json`.

### CODE REVIEW

**Comment by KurtStam** [comment]
@zregvart looks like the connectors version is set to 0.4-SNAPSHOT which makes a test fail.

**Comment by zregvart** [comment]
> @zregvart looks like the connectors version is set to 0.4-SNAPSHOT which makes a test fail.

It might need a new connectors release, I think we have `latest` as the version, let me debug this a bit...

**Comment by zregvart** [comment]
This is an issue in SQL stored connector, I've created https://github.com/syndesisio/connectors/pull/86. This PR should be updated when we release connectors.

**Comment by KurtStam** [comment]
retest this please

**Comment by KurtStam** [comment]
retest this please

**Comment by KurtStam** [comment]
@zregvart I think this may need a rebase now that the connector project is released.

**Comment by zregvart** [comment]
I've rebased this but I think the build will fail due to https://github.com/syndesisio/connectors/issues/88 so it will require a new version of connectors.

**Pull request merged**
