### PR TITLE
fix(github): Avoid duplicate repo generation

### PR DESCRIPTION
**Pull request by rhuss**

### CODE REVIEW

**Comment by jimmidyson** [comment]
retest this please

**Comment by jimmidyson** [comment]
flaky integration test...

**Comment by rhuss** [comment]
@jimmidyson can we merge it nevertheless? This fix is crucial ...

**Comment by jimmidyson** [comment]
retest this please

**Comment by jimmidyson** [comment]
let's give it one more time, I tried to fix it yesterday in a different pr

**Comment by jimmidyson** [comment]
Could not resolve any of the Camel fuse dependencies - is that a known issue? Don't mind merging this as-is and then updating Camel dependencies in subsequent PR.

**Comment by rhuss** [comment]
Hmm. jboss ea should be included. Let's merge first the camel update and let me do a rebase on this one.

**Comment by jimmidyson** [comment]
Yeah I'm guessing this is just that the version hadn't been promoted so had been purged after a while.

**Comment by zregvart** [comment]
retest this please

**Pull request merged**
