### PR TITLE
Sanitize component aliaes #630 #660

### PR DESCRIPTION
**Pull request by lburgazzoli**
The project generator now writes the syndesis.yaml like:

```yaml
---
flows:
- steps:
  - kind: endpoint
    uri: twitter-mention-connector:MENTIONS
  - kind: endpoint
    uri: http-get-connector?httpUri=www.google.com/2
  - kind: endpoint
    uri: twitter-search-1:cameltest?delay=1000&filterOld=true
  - kind: endpoint
    uri: twitter-search-2:camelprod?delay=1234&filterOld=true
  - kind: endpoint
    uri: http-get-connector?httpUri=www.google.com/1
```
So:
- if a connector is repeated but it does not have any component options, its scheme is preserved (see http-get-connector) 
- if a connector does have component options but it is not repeated, its scheme is preserved
- if a connector is both repeated and has component options, its scheme is suffixed with ``-${sequence}`` were the sequence is computed from the number of occurrencies of the connector

The generated secret follow a similar behavior:

```properties
# this is not repeated so no need to create aliases
twitter-mention-connector.accessToken=...
twitter-mention-connector.accessTokenSecret=...
twitter-mention-connector.consumerKey=...
twitter-mention-connector.consumerSecret=...

twitter-search.configurations.twitter-search-1.accessToken=...
twitter-search.configurations.twitter-search-1.accessTokenSecret=...
twitter-search.configurations.twitter-search-1.consumerKey=...
twitter-search.configurations.twitter-search-1.consumerSecret=...

twitter-search.configurations.twitter-search-2.accessToken=...
twitter-search.configurations.twitter-search-2.accessTokenSecret=...
twitter-search.configurations.twitter-search-2.consumerKey=...
twitter-search.configurations.twitter-search-2.consumerSecret=...
```

### CODE REVIEW

**Comment by jimmidyson** [comment]
@lburgazzoli LGTM - one PMD failure:

`PMD Failure: io.syndesis.controllers.integration.online.BaseHandler:31 Rule:AbstractClassWithoutAbstractMethod Priority:3 This abstract class does not have any abstract methods.`

**Comment by lburgazzoli** [comment]
retest this please

**Comment by lburgazzoli** [comment]
retest this please

**Comment by lburgazzoli** [comment]
retest this please

**Comment by lburgazzoli** [comment]
retest this please

**Comment by lburgazzoli** [comment]
retest this please

**Comment by rhuss** [comment]
retest this please

**Pull request merged**
