### PR TITLE
refactor: Update integration's step model for 'rule-filter' and 'filter' steps

### PR DESCRIPTION
**Pull request by rhuss**
As discussed in #451 the different kind of filter steps can now be already recognized by looking at `stepKind`.
("rule-filter" for a rule based defined filter, "filter" for a single expression filter)

Still open in this PR is the documentation. Would love to add it as swagger docs, but I'm afraid I won't make it before my PTO this week. So feel free to merge this PR first, so that the UI can continue to work on it.

### CODE REVIEW

**Comment by iocanel** [comment]
@rhuss: There are checkstyle violations.

**Comment by rhuss** [comment]
retest

**Comment by rhuss** [comment]
retest

**Comment by rhuss** [comment]
@iocanel how to trigger a retest ?

**Comment by iocanel** [comment]
plain old "retest this please" would do

**Comment by rhuss** [comment]
retest this please

**Pull request merged**
