### PR TITLE
fix: Allow snapshot deployments to the oss.sonatype.org mvn repos.

### PR DESCRIPTION
**Pull request by chirino**

### CODE REVIEW

**Comment by KurtStam** [comment]
@chirino why do we want SNAPSHOTS?

**Comment by jimmidyson** [comment]
I can't see any reason for this.

**Comment by chirino** [comment]
I don't see any reason to not support it.

**Comment by chirino** [comment]
At least with a snapshot, I can test out the script at: 
https://github.com/syndesisio/syndesis-s2i-image/blob/master/run.sh#L28

until a version gets released.

**Comment by chirino** [comment]
retest this please

**Comment by jimmidyson** [comment]
But we don't publish snapshots so we'd need to do that on each build too.

**Comment by chirino** [comment]
I wouldn't do snapshot deploys as part of CI builds.  It's just nice to have an option for a developer to push snapshot build to the repo in case he needs to use it in another project and avoid waiting for the release to get cut.   This is definitely in the special case territory.

**Comment by rhuss** [comment]
I think publishing of snapshots should never be an issue, only consuming it is a problem. I'm fine if people consume stuff temporarily without releasing snapshot dependencies. But that is checked during a release anyway. 

I just see this as a kind of 'scratch pad'. And CI shouldn't publish snapshots.

**Comment by rhuss** [comment]
retest this please

**Pull request merged**
